PREFIX : <http://qldarch.net/ns/rdf/2012-06/terms#>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
select distinct ?s ?p ?o  where {
    graph <http://qldarch.net/rdf/2013-09/catalog> {
        ?u <http://qldarch.net/ns/rdf/2013-09/catalog#hasAnnotationGraph> ?g.
    } .
    graph <http://qldarch.net/ns/rdf/2012-06/terms#>  {
       ?t rdfs:subClassOf :Relationship .
    } .
    graph ?g {
        BIND (?r AS ?s) .
        ?s a ?t .
        ?s :evidence _:e .
        ?s :subject <%s> .
        ?s :predicate <%s> .
        ?s :object <%s> .
        ?s ?p ?o .
    } .
}
